name: CI
on: 
  workflow_dispatch: #allows repo admins to trigger this workflow from the Actions tab
  pull_request_target:
  push:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: fastdotai/fastai2 #this is defined here: https://github.com/fastai/docker-containers/blob/master/fastai2-build/Dockerfile
    env:
      auto_fix: false  
    steps:

    - name: checkout contents of PR
      if: github.event_name == 'push'
      uses: actions/checkout@v2

    - name: checkout contents of PR
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}

    - name: Install libraries
      run: |
        pip install nbdev
        pip install -e .

    - name: Attempt to read notebooks
      run: |
        nbdev_read_nbs

    - name: Check if notebooks are clean
      id: clean
      run: |
        nbdev_clean_nbs
        if [ -n "$(git status -uno -s)" ]; then
          echo"::set-output name=forgot_to_clean::true"
          echo "::error::Detected notebooks that are not cleaned."
          echo "\n\nList of notebooks that are not clean:"
          git status -s
          exit 1;
        fi
  
    - name: Check that library syncs with notebooks
      id: lib
      run: |
        nbdev_diff_nbs > _nbdev_diff_logs.txt
        if [ -n "$(cat _nbdev_diff_logs.txt)" ]; then 
          echo "::set-output name=forgot_to_lib::true"
          echo "::error::Detected notebooks that are not in sync with the library."
          cat _nbdev_diff_logs.test
          exit 1;
          if [[ $auto_fix == 'true' ]]; then 
            nbdev_build_lib
          fi
        fi

    - name: Commit differences back to GitHub
      if: github.env.auto_fix == 'true' && ( steps.clean.outputs.forgot_to_clean == 'true' || steps.clean.outputs.forgot_to_lib == 'true' )
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add nbs && git commit --allow-empty -m'apply changes from `nbdev_clean_nbs`'
        git add fastai2 && git commit --allow-empty -m'apply changes from `nbdev_build_lib`'
        git push -f

    - name: comment on PR
      if: failure() && ( steps.clean.outputs.forgot_to_clean == 'true' || steps.clean.outputs.forgot_to_lib == 'true' )
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          var user = context.payload.pull_request.user.login;
          github.issues.createComment({
            issue_number: context.payload.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `👋 @${user}! We detected notebooks that are not stripped or that are out of sync with the library in this PR.\n\nYou need to run \`nbdev_install_git_hooks\` before submitting a pull request! For more information, see the [CONTRIBUTING](https://github.com/${{github.repository}}#contributing) guide.\n\nYou can see the logs of the tests that triggered this message in run [${{github.run_id}}](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}).`
          })

  upload:
    runs-on: ubuntu-latest
    container: fastdotai/fastai2 #this is defined here: https://github.com/fastai/docker-containers/blob/master/fastai2-build/Dockerfile
    steps:

    - name: download data
      run: |
        from fastai2.data.external import untar_data, URLs
        from fastai2.torch_core import parallel
        from pathlib import Path
        urls = ['ADULT_SAMPLE','BIWI_SAMPLE','CAMVID_TINY','CIFAR','COCO_SAMPLE',
                'COCO_TINY','IMDB_SAMPLE','LSUN_BEDROOMS','ML_SAMPLE',
                'MNIST_SAMPLE','MNIST_TINY','PASCAL_2007','PETS']
        url_list = [URLs.__dict__[k] for k in urls]
        parallel(untar_data, url_list, progress=True)
      shell: python

    - name: upload data to actions artifacts
      uses: actions/upload-artifact@v2
      with:
        name: fastai-data
        path: ~/.fastai

  test-notebooks:
    needs: upload
    container: fastdotai/fastai2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nb: ['[0-2]','[3-5]','[6-9]']
    steps:
    - name: checkout contents of PR
      uses: actions/checkout@v2
      if: github.event_name == 'pull_request_target'
      with:
        ref: ${{github.event.pull_request.head.ref}}
        
    - name: checkout contents of PR
      if: github.event_name == 'push'
      uses: actions/checkout@v2

    - name: Install libraries
      run: |
        pip install nbdev
        pip install -e .
        
    - name: download data
      uses: actions/download-artifact@v2
      with:
        name: fastai-data
        path: ~/.fastai
      
    - name: Test notebooks batch ${{matrix.nb}}
      run: |
        nbdev_test_nbs --flags '' --n_workers 4 --timing True --fname "nbs/[0-9]${{matrix.nb}}*.ipynb"
  
